### ISSUE TITLE
Does not work on Heroku

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#104]
I'm seeing issues like this on all review apps:

![image](https://user-images.githubusercontent.com/53387/104903213-033dcd80-5980-11eb-9718-af415d45b08f.png)

`error: no pg_hba.conf entry for host "54.91.8.233", user "qrsiljldhoxjis", database "d17e94jsledgnn", SSL off`

Heroku [requires SSL](https://devcenter.heroku.com/articles/heroku-postgresql#heroku-postgres-ssl) on Postgres connections. 

@Twixes any idea what might have changed? I remember this [TLS PR](https://github.com/PostHog/plugin-server/pull/88), but it only touched Kafka...

**Comment by Twixes** [comment]
Ahh, I don't think anything changed with our approach to Postgres-over-SSL. Did this use to work?

**Comment by mariusandra** [comment]
Yeah, plugins used to work on Heroku, but now they don't.

**Comment by Twixes** [comment]
Looks like Heroku review apps are actually working again (PostHog/posthog#3006 for instance), so I'm just going to go ahead and close this, but let's watch out for any problems of course.

**Comment by mariusandra** [comment]
Not in these 3 last PRs:
- https://posthog-2833-show-perio-avof30.herokuapp.com/project/plugins
- https://posthog-delete-annotati-nbqhdd.herokuapp.com/project/plugins
- https://posthog-readme-new-func-8o4xlz.herokuapp.com/project/plugins

So I'd keep this open for a bit longer.

**Comment by mariusandra** [comment]
This now works, right? 🎉

**Comment by Twixes** [comment]
Yep
