### ISSUE TITLE
Do not load plugins for teams that have the plugin server disabled

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#105]
If you enable plugins on a project, install and activate some plugins, and then disable plugins on that project, these plugins still get loaded (VMs created, etc) in the plugin server. The `processEvent` and similar functions will not get called, but `setupPlugin` and all scheduled functions will.

**Comment by Twixes** [comment]
I'm a bit unsure about the scope here, because as far as I understand we are targeting having the plugin server enabled for _every_ team, seeing that we want it to take over all of event processing. So it's only about more deliberate creation of VMs?

**Comment by mariusandra** [comment]
That's where we want to be, but plugins will still probably be opt in for at least a sprint or two... And this is a bug until then. 

Basically disabling plugins on the team should act as a kill switch for all plugin configs on the team. Even if it's the plugin server doing the ingestion.
