### ISSUE TITLE
Respect `team.anonymize_ips` earlier in the pipeline and hide IPs from plugins

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#119]
We store the IP address of the user calling `posthog.capture` inside the `$ip` property. If this property exists, we use it. If not, we take the IP from the request and put it in the property.

When the event passes through plugins, we pass along the request's IP, all the way until ingestion. If a plugin wants to export the event to another database, it'll also have access to and send the request's IP, not the provided `$ip` property.

Solution: we should override the IP earlier in the pipeline, as to prevent storing PII that we don't want.

**Comment by yakkomajuri** [comment]
Somewhat related to this I had a user yesterday who wanted to be able to not capture IPs at all, whereas if they don't set an IP themselves (like `0.0.0.0`) we end up setting it for them if they want it or not.

**Comment by mariusandra** [comment]
If `team.anonymize_ips` is set, we also shouldn't capture IPs. Is that not the case?

**Comment by yakkomajuri** [comment]
Ah right - I guess the setting has a bit of a misleading name.
