### ISSUE TITLE
Minimum PostHog version for plugins

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#12]
I'd like to specify a minimum posthog version in my plugins to make sure all the required functionality is there. For example to say "my plugin requires attachments, so I need at least PostHog 1.17.0". It might also be good to pin to an exact version of posthog, since we might still have some slightly breaking changes.

The `engines` field in package.json seems to be a great place for this.

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines

**Comment by mariusandra** [comment]
I've been thinking about version numbers a bit and came to the conclusion that we should pin plugins to versions of `posthog-plugin-server` and not versions of `posthog` itself.

My arguments is that Posthog versions go `1.x.0` --> `1.(x+1).0` --> `1.(x+2).0`, etc. Between one `x` --> `x+1` we can have anything between a) breaking changes to plugins to b) no changes to plugins at all. This means I can't tell my plugins to be "> 1.16.0", since "1.19.0" might introduce a breaking change while `1.17` and `1.18` won't. This in turn means as a plugin author I need to release a new version of my plugin any time a new posthog version comes out. This is not sustainable.

The versions of posthog-plugin-server could independently follow semver and make it clear when there are breaking changes and when there are none. We might also just release version 1.0.0 together with PostHog 1.18.0... and remain mindful of breaking changes. 

With that schema, if 1.0.0 is the plugin server pre-attachments and 1.1.0 post-attachments, I could pin the maxmind plugin to "^1.1.0" and make sure it won't be installed on earlier versions. No other plugins will need their engine versions updated as they don't use attachments.

**Comment by mariusandra** [comment]
The API for plugins has stabilised somewhat and we will do our best not to have breaking releases anymore. That means all plugins written for 1.23 should work in 1.43 and the same for all versions in between.

Therefore the previous discussion about pinning to a version of `@posthog/plugin-server` is not as valid anymore. From a users's standpoint, it makes sense to pin a plugin to a version of PostHog itself, and not some "internal" library like the plugin server.

Now that we also have all plugin config in `plugin.json`, we're free to structure the version requirement as needed.

How to do it? Here are some options. Does any of them speak to you?

```json5
// Option 1
{
  "name": "Hello World",
  "url": "https://github.com/PostHog/helloworldplugin",
  "description": "Greet the World and Foo a Bar, JS edition!",
  "main": "index.js",
  "dependencies": {
    "posthog": "> 1.23.0"
  },
  "config": []
}

// Option 2
{
  "name": "Hello World",
  "url": "https://github.com/PostHog/helloworldplugin",
  "description": "Greet the World and Foo a Bar, JS edition!",
  "main": "index.js",
  "requirements": {
    "posthog": "> 1.23.0"
  },
  "config": []
}

// Option 3
{
  "name": "Hello World",
  "url": "https://github.com/PostHog/helloworldplugin",
  "description": "Greet the World and Foo a Bar, JS edition!",
  "main": "index.js",
  "versions": {
    "posthog": "^1.23.0"
  },
  "config": []
}

// Option 4
{
  "name": "Hello World",
  "url": "https://github.com/PostHog/helloworldplugin",
  "description": "Greet the World and Foo a Bar, JS edition!",
  "main": "index.js",
  "posthogVersion": ">= 1.23.0",
  "config": []
}

// Option 5
{
  "name": "Hello World",
  "url": "https://github.com/PostHog/helloworldplugin",
  "description": "Greet the World and Foo a Bar, JS edition!",
  "main": "index.js",
  "posthog": "~> 1.23.0",
  "config": []
}

// Option 6
{
  "name": "Hello World",
  "url": "https://github.com/PostHog/helloworldplugin",
  "description": "Greet the World and Foo a Bar, JS edition!",
  "main": "index.js",
  "minPostHog": "1.23.0"
  "config": []
}
```

All other options also welcome. The version string itself should probably be a package.json style semver string.

I don't think we should show this version requirement in the interface for now. If we would want to, we must update the `repository.json` file with versions for each plugin, and must remember to always keep it in sync when this info changes due to plugin updates. Thus I propose to just keep it locally in `plugin.json` for now.

This means that we can alert about the wrong version only when clicking "install" or "upgrade" next to a plugin. Django would have to download the archive, check `plugin.json` inside and throw an error if we're running a version that's too old. This won't be great UX, but it will be effective, considering most plugins will work with your version anyway.

**Comment by timgl** [comment]
Option4 seems most obvious to me

**Comment by Twixes** [comment]
4 sounds good to me
