### ISSUE TITLE
Handle errors thrown inside plugins

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-server#131]
Currently if a plugin method throws an error, it will bubble up the server and get caught by Sentry ([like this](https://sentry.io/organizations/posthog/issues/2169746991)). We should logs these errors in a smarter way, so that they can be useful to plugin users _and_ don't pollute our Sentry data.

**Comment by Twixes** [comment]
We probably should resolve #72 before and use that solution here too.

**Comment by mariusandra** [comment]
These errors do get captured via `processError` and stored on the plugin config table. #146 silenced them, so closing.

#72 is a separate topic and will definitely enhance error collection!
