### ISSUE TITLE
Cannot use a pool after calling end on the pool

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#139]
Not sure why this happens

- [Sentry error 1](https://sentry.io/organizations/posthog/issues/2207351764/?project=5592816&query=is%3Aunresolved)
- [Sentry error 2](https://sentry.io/organizations/posthog/issues/2205859685/?project=5592816&query=is%3Aunresolved)

**Comment by Twixes** [comment]
I think it may happen during reloads after `closeServer`. To be investigated further some time though

**Comment by mariusandra** [comment]
Happened 3 months ago and no more since. Closing.
