### ISSUE TITLE
Outgoing webhooks

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-server#145]
Basically, we need to make this https://posthog.com/docs/integrations/slack be done inside of this https://github.com/PostHog/plugin-server.

The rationale is that in the current setup webhooks are fired with raw incoming events in the capture endpoint. They should instead be fired with the final event, as processed by plugins. We could also possibly smooth out some reliability issue just by the fact of refactoring.

Would be super cool done as a plugin, but there are two considerations that complicate this is if we want no regressions:
- the plugin would have to allow selecting only firing the webhook for specific actions,
- the format would have to customizable per specific action.

**Comment by Twixes** [comment]
A prerequisite for this is #157.

**Comment by yakkomajuri** [comment]
I believe this is done? @Twixes

**Comment by Twixes** [comment]
Indeed!
