### ISSUE TITLE
Use labels to create releases

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#150]
When a label like `version:patch` is added to a PR, actually release a new patch version of the plugin server when it lands in master.

**Comment by Twixes** [comment]
Why not just bump version in package.json? It's the same amount of work and no additional code

**Comment by mariusandra** [comment]
Then you can't revert PRs easily

**Comment by Twixes** [comment]
That's true. Though I like the explicitness of a quick separate PR for version bump. And we don't accrue lots of one-off labels in https://github.com/PostHog/plugin-server/labels

**Comment by mariusandra** [comment]
Hmm, the way I envision it: we tag a PR with a label `"patch version"`, `"minor version"` or `"major version"` (those words, not `"version 0.8.4"` or anything specific) and after it's merged, the package publishing action in master just runs `npm version patch` or something before.

**Comment by Twixes** [comment]
Oh, yeah, that's good. At that point we'll probably need to write a separate GH actions for this release complexity though, because `cd.yml` is getting pretty big. 😅

**Comment by Twixes** [comment]
Done!
