### ISSUE TITLE
Do action matching in plugin server

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-server#157]
If we match fully processed events to actions in the plugin server (in parallel with saving the event to DB), we'll be able to again have asynchronous events>actions matching. Even more importantly, we'll be able to support method `onAction(action: Action, event: PluginEvent)` on plugins, facilitating making webhooks a plugin. In the long run something like https://github.com/PostHog/posthog/issues/3357 may be built on top of this.

**Comment by mariusandra** [comment]
How much effort will this be? I guess we need the entire filtering logic (that is probably already implemented twice in django? Once for postgres and once for clickhouse?)... into JS. Sounds like a lot of meticulous work...

**Comment by Twixes** [comment]
The logic is actually common, because we perform matching on a temporary event created in **Postgres** (as storing action definitions in ClickHouse is a pain).
