### ISSUE TITLE
Replace io-REDIS

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#178]
Last night I spent way too long trying to track down an impossible bug in the plugin server, which turns out to be caused by a [bug in ioredis](https://github.com/luin/ioredis/issues/634/).

Basically, the following line would get stuck forever one time out of a thousand:

```js
const hooksCacheKey = `@posthog/plugin-server/hooks/${team.id}`	
const hooksCacheValue = await this.pluginsServer.redis.get(hooksCacheKey)	
```

[Removing any mention of redis](https://github.com/PostHog/plugin-server/commit/96b411c4cf4b87f4798e125fc33e874cb8b42714) from the ingestion pipeline solved the issue. 

However, various plugins still use redis and we can't just have them [stalling randomly](https://sentry.io/organizations/posthog/issues/2225338177/?project=5592816&query=is%3Aunresolved) like they now still sometimes do:

![image](https://user-images.githubusercontent.com/53387/108477559-a8a3d400-7293-11eb-9ef2-202277315000.png)

Luckily plugins now [have timeouts](https://github.com/PostHog/plugin-server/pull/155) and this doesn't do more than stall the ingestion for 30sec... and leave some open handles hanging. 

Still crashing for no reason is not acceptable, even it it's one time in 100k. 

What to do? Fix the [bug in ioredis](https://github.com/luin/ioredis/issues/634/)? Replace [ioredis](https://github.com/luin/ioredis) with [redis](https://github.com/NodeRedis/node-redis)?  

I think [celery.node](https://github.com/actumn/celery.node) required ioredis for some reason, but since we have integrated that code into our codebase, perhaps we can work around it... or even use both libraries interchangeably (one for celery, one for other uses)... And perhaps switching the redis library won't help at all? But I'm not sure what to do then.

**Comment by macobo** [comment]
Flyby thought: Perhaps there are some options in the redis library which cause/can help us avoid these issues? https://github.com/luin/ioredis/blob/0b001e0f3313ad53e9f62a8ab3a70c478205698b/lib/redis/index.ts#L51-L90

It does sound like some sort of a 'infinite retry' bug, e.g. with commands or connections?

Perhaps even maxRetriesPerRequest which is currently set to -1? https://github.com/PostHog/plugin-server/blob/bb8dfba4d83d068cbc497f11fcb85f0cc1ebff2d/src/server.ts#L37

**Comment by mariusandra** [comment]
Appreciate the outside perspective, but I'm not sure if that would help. The [PR to try to fix this](https://github.com/luin/ioredis/pull/658) writes "maxRetriesPerRequest does not help with this" :).

It seems to be getting stuck behind some socket connection issue and does not even try to retry.

I think the first step in resolving this would be to abstract all the redis calls into `db.ts` and wrap them all with timeouts to be sure that *all* the crashes are due to this.... and the next step would be to swap it out for another redis library to see if that makes and difference...

**Comment by mariusandra** [comment]
Still pending final analysis, but it seems like [introducing connection pooling](https://github.com/PostHog/plugin-server/pull/204) was the real answer.

`ioredis` is by far the best nodejs redis library and it would have been a shame to swap it out for something older and unmaintained... or new and untested.

**Comment by mariusandra** [comment]
Connection pooling seems to have worked. The rate of errors dropped drastically and the ones still remaining seem to be related to shutdowns: #210
