### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#219]
Due to some timing issue, we sometimes get tests flaking here:

![image](https://user-images.githubusercontent.com/53387/109292673-06539580-782b-11eb-920e-b844638824fb.png)

(and one other place where we expect 4, but get 5 CH persons)

**Comment by macobo** [comment]
What do you think about bypassing kafka and using a clickhouse driver in _most_ tests similar to how posthog/ repo does it? This should significantly reduce timing issues and flakiness and make the suite just a tiny bit faster. :)

**Comment by mariusandra** [comment]
I added `FINAL` and these tests work now. Plus fixed a bunch of other flakes. So closing for now.

Re the comment, I'm generally opposed to The Volkswagen Approach, where we have something totally different running in the tests, compared to what would run in production. :)
