### ISSUE TITLE
Plugin server is NOT working on Heroku

### ISSUE THREAD

**Issue by avorio** [PostHog/plugin-server#232]
Folks,

The plugin server associated with my instance of PostHog is NOT alive on Heroku, despite the `worker` dyno being active and running for the past many weeks. How do I troubleshoot this, please?

I'm running version 1.21.0 of PostHog but I'm worried about migration to the latest version before sorting this out.

Thanks!

**Comment by avorio** [comment]
Ah-ha! I found something in our logs:

```
2021-03-05T21:14:42.037011+00:00 app[worker.1]: [MAIN] 💥 Launchpad failure! error: no pg_hba.conf entry for host "XXXX", user "XXXX", database "XXXX", SSL off
```

Could this be it?

**Comment by Twixes** [comment]
Yes, thank you for the logs! Let's move this party to PostHog/posthog#3592.
