### ISSUE TITLE
Last chance to change the plugin structure

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#242]
We currently have:

```js
function setupPlugin(meta) {
}

function processEvent(event, meta) {
}

function processEventBatch(batch, meta) {
}

function runEveryMinute(meta) {
}

function runEveryHour(meta) {
}

function runEveryDay(meta) {
}
```

I think this makes plugins easy to write. 

However there are some issues with this approach:
- It's hard to create a structure that enables effortless TypeScript support (we must minimally return an object for that)
- Possible future namespace conflicts if we introduce new plugins (e.g. a user defines `runEvery2Minutes`, calls it from `runEveryMinute` on every other minute... and later we decide to introduce support for any `runEvery*` combination.
- Unclear from users if they can write their own random functions (what happens if I just write `const loadDb = async () => { .. }`. Will this specific function do something in the future?

But, still, having it in simple functions is easy to explain and to get started with.

Alternatively, we could introduce some syntax like:

```js
// importing is optional, but can help with scoping, TS and tests
import { on, process, schedule } from '@posthog/plugin-scaffold'

on('init', (meta) => {
})

process('event', (event, meta) => {
})

process('eventBatch', (batch, meta) => {
})

schedule('every minute', (meta) => {
})

schedule('5 * * * *', (meta) => {
})

schedule('everyDay', (meta) => {
})
```

or

```js
class MyPlugin extends PostHogPlugin {
    constructor() {
        // init
    }
  
    processEvent() { ... }
    processEventBatch() { ... }

    // ...
}
```

or 

```js
module.exports = {
    setupPlugin: async ({ config }) => {
    },
    processEvent: async (event, { config, cache }) => {
    },
}
```

or 

```js
/// ???
```

We can always change later and keep backwards compatibility for a long time to come... but there may be some decisions we should still do within the "plugins out of beta" task. Yet definitely not in time for 1.23, so if we decide to think this through, we should keep the `beta` label for another cycle or two.

Personally, I think the `on(event, callback)` approach is quite approachable.

**Comment by mariusandra** [comment]
One more:

```js
import { setupPlugin, processEvent, runEveryMinute } from '@posthog/plugin-scaffold'

setupPlugin((meta) => {
})

processEvent((event, meta) => {
})

runEveryMinute((meta) => {
})
```

**Comment by Twixes** [comment]
I'm not sure if it's worth it to restructure things so much at this point. Though it is a bit enticing. Considering the options:

IMO the drawback to `on(event, callback)` is that `event` would be a `string`, which is less clear than just function named e.g. `onEvent`. Also, `on` doesn't convey that this is not just an event listener, but a pipeline.

I like the
```TypeScript
module.exports = {
    setupPlugin: async ({ config }) => {
    },
    processEvent: async (event, { config, cache }) => {
    },
}
```
idea because basically it's what we do already. And if someone wants typing, it's as simple as
```TypeScript
import { Plugin } from '@posthog/plugin-scaffold'

const plugin: Plugin = {
    setupPlugin: ...
}

module.exports = plugin
```
This already is a thing.

Something I think we really should rework is periodic functions. They're very inflexible with `runEveryX`. This is where something like `schedule('5 * * * *', (meta) => ...)` would be much better for the future.

**Comment by mariusandra** [comment]
Hey, few thoughts from this:

1) Now that we have babel, the scoping is actually easy to solve with: `export function processEvent` and `function calculateInternalData`. Calling `export` should convert it to `module.exports` itself. This won't help typing, but it's already something. We could update [these lines](https://github.com/PostHog/plugin-server/blob/d3813acc3e049ce817147fe1f37e180e0fc4a7bc/src/vm/vm.ts#L92-L93) to ignore `global` if module.exports is set... and fetch from `global` only as a fallback if nothing is explicitly exported

2) What about this?
```js
export const schedule = { 
    '5 * * * *': (meta) => {},
    'every minute': (meta) => {} 
}
```

3) It's not `on(event, callback)`, but `process(event, callback)` especially because `on` seems like a listener and not returning from a listener seesm like a fine thing to do

**Comment by Twixes** [comment]
I like the `schedule` idea. I think we should implement it.

**Comment by mariusandra** [comment]
This is also the last chance to change the structure of PluginEvent. For example in the Snowflake and BigQuery exports we have a separate field for $set and $set_once. Initially because bigquery is not a big fan of nested properties, but later on this just looks more practical for understanding what's happening...

<img width="1471" alt="Screenshot 2021-04-15 at 01 37 50" src="https://user-images.githubusercontent.com/53387/114793715-4941dc00-9d8b-11eb-9e3e-a43e5903088c.png">

Do we want to split these out for everyone? Not sure... but worth a though perhaps.

**Comment by Twixes** [comment]
`set` and `set_once` directly on `PluginEvent` looks pretty good, though not sure if worth the added complexity of supporting both this and `properties` approach.

**Comment by mariusandra** [comment]
I realised we could improve one more thing regarding the plugin structure: composability.

Here's an example of what I mean: I'd like to import from `@posthog/plugin-contrib` a method `createBatchedExportPlugin` and I want my entire plugin to be like this (ignore the implementation details):

```js
import { createBatchedExportPlugin } from '@posthog/plugin-contrib`

createBatchedExportPlugin({
  filter: event => "currency" in event.properties,
  maxSize: '1MB',
  maxCount: 100,
  upload: (events) => fetch('/api/post', { events }),
})

function setupPlugin(event) {
  console.log('starting')
}
```

I *could* already make this work. The `createBatchedExportPlugin` function could already look like this (not tested though):

```js
function createBatchedExportPlugin({ filter, upload, maxSize, maxCount }) {
  module.exports.setupPlugin = (meta) => meta.global.batch = createBatch({ upload, maxSize, maxCount }) 
  module.exports.onEvent = (event, meta) => { if (filter(event)) { meta.global.batch.add(event) } }
  module.exports.teardownPlugin = () => batch.flush()
}
```

However, if then the plugin author adds a manual `onEvent` or whatever function, the one our "plugin plugin" defined will be overwritten.

Thus some `registerPluginFeature('setupPlugin', () => {})` system still makes *some* sense. 

Or it could be:

```js
import { createBatchedPlugin } from '@posthog/plugin-contrib`

const importedPlugin: Plugin = createBatchedPlugin(...)
registerSidePlugin(importedPlugin)
```

... where we can have multiple `Plugin`-s per "plugin". 

I'm not 100% sure how this should work, but I do see this giving us the power to make composable plugins, where you add a few lines and automatically get scheduled jobs that manage exports via the PostHog API 

I don't like it when there are two ways to accomplish the same thing, but it might be ok here.

More questions than answers above, but 🤷
