### ISSUE TITLE
Pipe plugin errors to stdout on DEBUG

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/plugin-server#254]
When developing locally, it would be nice to get the errors that we show on the `ERROR` tag in the UI on the terminal as well. 

cc @kpthatsme

**Comment by mariusandra** [comment]
I think this is solved in https://github.com/PostHog/plugin-server/pull/318

**Comment by Twixes** [comment]
Actually this wasn't solved in that PR in order to make it smaller. PR #333 addresses this use case.
