### ISSUE TITLE
Long posthog_team table rows slow down ingestion

### ISSUE THREAD

**Issue by macobo** [PostHog/plugin-server#257]
The slowest query in plugin server by far is `SELECT * FROM posthog_team WHERE id = $1`. We spend more time on this query than on all other postgres queries combined (!) in plugin server.

![image](https://user-images.githubusercontent.com/148820/111531769-a424eb00-876d-11eb-963b-1c4d57ebc9ca.png)

It's not slow due to the query, but rather deserialization. Some columns are just that wide, for example we have a team whose `event_names_with_usage` column is 500k characters long.

We should fix this.

**Comment by macobo** [comment]
Did some more measurements:

```
d25vf5hht9th9v> SELECT length(event_names_with_usage::text), length(event_properties::text), length(even
 t_properties_numerical::text), length(event_names::text), length(event_properties_with_usage::text) FRO
 M posthog_team order by length(event_names_with_usage::text) DESC LIMIT 10;
+----------+----------+----------+----------+----------+
| length   | length   | length   | length   | length   |
|----------+----------+----------+----------+----------|
| 574206   | 560      | 105      | 338915   | 2237     |
| 75717    | 58       | 2        | 23186    | 311      |
| 43815    | 439      | 2        | 26553    | 1639     |
| 22731    | 1099     | 325      | 16035    | 4236     |
| 17022    | 1372     | 110      | 6174     | 6422     |
| 16833    | 3862     | 1723     | 7919     | 14233    |
| 15590    | 5738     | 287      | 6412     | 11302    |
| 13981    | 31       | 2        | 7126     | 160      |
| 11744    | 1366     | 510      | 4656     | 5307     |
| 10773    | 577      | 145      | 5135     | 2176     |
+----------+----------+----------+----------+----------+
SELECT 10
Time: 0.227s
```

The problematic (large) columns are `event_names_with_usage` and `event_names`, weighing ~1MB in total for the largest user. This is downloaded for every event, which results in significant load.

These columns are used in the FE to display information/stats about events.

Plugin server has the logic to populate these columns, [making them currently needed to be read](https://github.com/PostHog/plugin-server/blob/a0179ba/src/ingestion/process-event.ts#L415-L454). The corresponding logic in main app can be found [here](https://github.com/PostHog/posthog/blob/84d853748d45f9b4cc8b593f17c9fe228a58dee0/posthog/tasks/process_event.py#L78-L101).

A fix for this issue should reduce the amount of data read whilst keeping the number of writes (only done when anything changed) consistent. I think the proper way to do this is to normalize the schema (new table for this logic) and to do caching + idempotent writes in the plugin server.

Given that this is tricky to do until the old ingestion code still lives, I think this is only worth doing when we're bottlenecked by postgres in ingestion and occasionally accumulating backlog.

**Comment by macobo** [comment]
This has been solved by adding per-worker caching. Note there's still some races in actually populating the values - a schema migration might fix that.

From the below graphs you can see the before-after for how much time is spent by workers querying the db (per minute) and breakdown of queries. 

Top two costliest queries overall (fetching teams + if they have hooks) are now negligible in terms of cost.

![image](https://user-images.githubusercontent.com/148820/112124077-a30b1800-8bca-11eb-9146-2967d0cc7c15.png)
![image](https://user-images.githubusercontent.com/148820/112124118-ad2d1680-8bca-11eb-9c1f-5d7916a0192b.png)

A side-effect of this is that plugin servers do a _lot_ less inbound network traffic.

Prior to the change we did 180MB/s during peak or ~80MB/s during non-peak times of inbound traffic to plugin servers. This was reduced to 7-8MB/s currently, a 10-25x reduction.

![image](https://user-images.githubusercontent.com/148820/112124811-6f7cbd80-8bcb-11eb-829b-857a3d99969a.png)

Not sure if this translates into any direct cost savings though, cc @fuziontech?

**Comment by fuziontech** [comment]
This is huge. All of the queries to Postgres not only cost money in inter-AZ networking to heroku, but also in bytes through the ELB for the pgbouncer. The less data we grab, and then more that we cache that data, the better, faster, and cheaper!
