### ISSUE TITLE
Plugin audit log on events

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#269]
Currently if for example one export plugin stops working (export server throws 500), the plugin is ignored and we won't know what event it is unless we do a full diff for event IDs in both posthog and the export destination.

There should be an easier way. Building support for retries ([comment below the line here](https://github.com/PostHog/plugin-server/issues/156#issue-809224435), [internal discussion](https://posthog.slack.com/archives/C01F6QWTVB5/p1616390397000800)) would solve this, however just keeping a history of what plugins were applied to an event will give us enough information to make due in case of emergency.

I imagine we will just set a property on the ingested event, something like `event.properties['$plugins_ran'] = []` and `event.properties['$plugins_failed'] = []` and then push something to those arrays after plugins run. For example `event.properties['$plugins_failed'].push(`${plugin.id}-${toSlug(plugin.name)}`)...

This has not been asked by any user yet, though it might be useful to implement regardless.

**Comment by Twixes** [comment]
I think this was addressed in #327.
