### ISSUE TITLE
Don't process $snapshot via plugins

### ISSUE THREAD

**Issue by macobo** [PostHog/plugin-server#280]
Provocative title, I know.

Currently $snapshot events are treated like any other and processed by plugins. However:
1. Modifying the payload data could easily break the session recording feature or display misleading information on the screen.
1. The data payload is chunked and compressed - making it hard to make anything out of it.
1. The payload data contains pretty large data that we need to serialize to send back-and-forth from consumer to worker to VM and back again - this hurts performance.
1. Plugin authors might not know about treating $snapshot events in a special way.

The only usecase for plugins is syncing it to other data sources and playing back via rrweb there.

I'd propose ignoring snapshot events for now and in the future perhaps add a `processSnapshotBatch` or similar function to plugins if the syncing scenario comes up. This function would not be allowed to modify the data though.

**Comment by mariusandra** [comment]
Import and export plugins are the only ones that legitimately need to access this event. Handling them in a separate `processSnapshot` function makes sense and shouldn't be too hard to implement. 👍 for skipping them in `processEvent`.

Regarding `processSnapshotBatch`, this is a side quest and better suited for #242, but we might benefit from deprecating `processEventBatch` altogether. In reality, in a well performing system, 99% time when `processEventBatch` gets called, it gets just one event. The original motivation behind this function was that you for example get 100 events at once and then upload them to S3 or wherever. In reality, this won't really work. The bigquery export for example uses some internal buffering queue to batch its uploads... and we'll need something similar for S3. (Plus a `onShutdown` function to flush it... but that's another story)

**Comment by yakkomajuri** [comment]
Interestingly, I had a call with a user recently about this. He would want to actually do some processing on session recording events.

We should probably make a determination otherwise people could actually start writing plugins that target `$snapshot` events

**Comment by mariusandra** [comment]
@yakkomajuri what kind of processing was this user looking at?

If nothing substantial, I'd propose we:

- remove `$snapshots` from `processEvent`. 
- implement the async `onEvent` as discussed here: https://github.com/PostHog/plugin-server/issues/328
- implement a async `onSnapshot` to complement `onEvent` that just gets session recording events. Plugin authors can choose what to target, or both (`export const onSnapshot = onEvent`)
