### ISSUE TITLE
Downloading the geoip database too many times

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#296]
Maxmind releases a new IP database once per month, yet the plugin server now eagerly downloads a new one every time it runs due to the 14 day period I seem to be hitting:

![image](https://user-images.githubusercontent.com/53387/113709487-d2e60f80-96e2-11eb-90c4-e8ffa1b61718.png)

Related: right now we download and load the database for everyone, including users who haven't and won't enable the geoip plugin. Because it does add quite a bit of memory overhead, we should lazily load the plugin data into memory when we actually need to use the plugin (e.g. when `locate` gets called).

**Comment by mariusandra** [comment]
Related issue: https://github.com/PostHog/posthog/issues/3888

Here's a thought. To avoid wasting this much memory, we could only load the geoip database in the main thread, and run `geoip.locate(event.ip)` directly on each event (e.g. in the main thread kafka/celery queue), passing the result into `meta` for plugins to use.

**Comment by Twixes** [comment]
I believe the problem that turned as off from lazy loading was that it would stall the entire ingestion pipeline, and with our current 30 s timeout that could mean some ingestion failures.

**Comment by Twixes** [comment]
I think we should be fine with the main-thread-only idea. And increase staleness threshold to something like 45 days.
