### ISSUE TITLE
Team Extensibility release 1.25.0 bis

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#330]
Spillover to finish still this week:
- Get rid of event_names: [], event_properties: {}, etc - https://github.com/PostHog/posthog/issues/3726 (Marius)
- Get the basic retry queue fully tested and running on cloud (with the postgres backend) - https://github.com/PostHog/plugin-server/pull/325 (Marius)
- Clean up all the old ingestion code. (Michael)
- Get the plugin logs live (Michael + Karl)

---

Next sprint bigger plugin work:
- Add more retry queue backends (S3, clickhouse) (Marius) https://github.com/PostHog/plugin-server/pull/325
- Add support for automatic retries of processEvent and other functions (Marius) https://github.com/PostHog/plugin-server/issues/273
- Split `processEvent` and `onEvent`, create `onSnapshot` (Yakko) https://github.com/PostHog/plugin-server/issues/328
- Move event->action mapping to plugin server. Move webhooks over. Implement `onAction` (Michael) https://github.com/PostHog/plugin-server/issues/235
- Plugins during the onboarding flow? https://github.com/PostHog/posthog/issues/3764

New plugins and updates: (Yakko & Marius?)
- Downsampling https://github.com/PostHog/posthog/issues/3365
- PostHog to PostHog https://github.com/PostHog/plugin-repository/issues/19
- Postgres export https://github.com/PostHog/plugin-repository/issues/11
- Fix rudderstack export https://github.com/PostHog/plugin-repository/issues/15
- Solidify first time event tracker and maybe add to core https://github.com/PostHog/plugin-server/issues/315
- Add session end to session tracker plugin https://github.com/PostHog/session-tracker-plugin/issues/1 

Integrations -> Python (Yakko?) & Ruby (Marius?).
- python: $set_once to the python library https://github.com/PostHog/posthog-python/pull/23 and sentry support https://github.com/PostHog/posthog-python/pull/13 and other missing features
- ruby: add feature flags, $set and $set_once, modernise what can be modernised

**Comment by yakkomajuri** [comment]
Ok so I'm happy to pick up what was laid out for me here, but with the caveat of low expectations, given I'm off Monday, will be support hero next cycle and still have onboardings to do.

I'd prioritize:
1. `onEvent` #328 
2. `$set_once` + Sentry to Python lib
3. Building more plugins if time allows

Other thins I'd like to highlight, for this release or next:
- https://github.com/PostHog/posthog-js/issues/214
- https://github.com/PostHog/posthog-js/issues/199
- Full API support inside plugins: I need to write up an issue with some ideas for this, probably something I can tackle the cycle after

**Comment by yakkomajuri** [comment]
As for spillover, I also have #322 and #324. I believe #327 is getting in when tests pass

**Comment by Twixes** [comment]
Personal list for now, in decreasing order of workload (will see what I manage to cross out on Friday still):

- Definitely can look into an `onAction` implementation but it not a trivial thing, and not compatible with an MVP approach – it must work just and exactly as well as currently in Django, else it's a regression. So I'll spec this out exactly (one thing that I could have done better when porting ingestion – while the task is simple to describe, the scope of implementation is actually _large_, and various intricacies matter).
- Make the GeoIP and first event tracking plugins preinstalled, with plugins shown during onboarding.
- Get example plugins in order – hello world and the starter kits I made some time ago (which weren't really very useful).
- Finish data sendoff plugin from PostHog Cloud to playground.
- `set_once` GeoIP data on persons.

Then from other things, plugin logs and deprecated code removal are done, just need to merge (most importantly logs require coordination with infra before merging – we should be fine with a bit of a wait though).

**Comment by mariusandra** [comment]
All right, thanks for the input! I have added our combined thoughts into the next release: https://github.com/PostHog/posthog/issues/4089
