### ISSUE TITLE
Update documentation for 1.25

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#356]
We're going to have a lot of new stuff with plugins for 1.25. The docs need to be updated and a consolidated list of improvements made for the readme. Plus all the new plugins.

**Comment by mariusandra** [comment]
What was built?

- Add `onEvent`
- Add `onSnapshot`
- Deprecate `processEventBatch`
- Added job queues
- Downsampling plugin
- Snowflake export (did we mention it?)
- ...

Edit this list as needed.

**Comment by Twixes** [comment]
More:
- `$snapshot` events no longer go through `processEvent`
- Added `console` logs in UI
- `teardownPlugin` is more predictable, runs on reload to
- There's a list of `import`able packages, should be documented with provided versions
- GeoIP plugin is preinstalled

**Comment by yakkomajuri** [comment]
And now `$set` and `$set_once` support in Python (extensibility, not plugins)
