### ISSUE TITLE
yarn start:dev is hanging (running on M1)

### ISSUE THREAD

**Issue by buwilliams** [PostHog/plugin-server#370]
I can start the plugin server on M1 with `yarn build; WORKER_CONCURRENCY=2 yarn start:dist`
but
Running `yarn start:dev` hangs with this output:

[INFO] 06:56:59 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.2)
[MAIN] 06:57:05 ⚡ @posthog/plugin-server v0.20.1
[MAIN] 06:57:05 ℹ️ 2 workers, 10 tasks per worker
[MAIN] 06:57:05 ✅ Connected to Redis!
[MAIN] 06:57:05 🚶 Connected to job queue producer "graphile"
[MAIN] 06:57:05 🔁 @posthog/mmdb is 48 days old, which is more than the staleness threshold of 45 days, refreshing in the background...
[MAIN] 06:57:05 ⏳ Downloading GeoLite2 database from PostHog servers...
[MAIN] 06:57:05 🪗 Decompressed GeoLite2-City-2021-03-23.mmdb.br from 21.9 MB into 63.1 MB
[MAIN] 06:57:05 🗺 Starting internal MMDB server...
[MAIN] 06:57:05 👂 Internal MMDB server listening on port 58270
[MAIN] 06:57:05 ⏰ Starting scheduling service...
[MAIN] 06:57:06 ✅ Downloaded GeoLite2-City-2021-03-23.mmdb of 21.9 MB
[MAIN] 06:57:07 💾 Saved GeoLite2-City-2021-03-23.mmdb into the database
[MAIN] 06:57:07 🪗 Decompressed GeoLite2-City-2021-03-23.mmdb from 21.9 MB into 63.1 MB
[MAIN] 06:57:07 💉 Injected fresh @posthog/mmdb

**Comment by macobo** [comment]
(Was working with buddy through this) - my suspect is ts-node running into issues since I've seen that before on this project.

**Comment by mariusandra** [comment]
Everything obviously works for me on my M1, so this seems like a fun thing to debug :).

@buwilliams how did you install node? I think I actually have an old (pre M1 homebrew) NodeJS 15 that's compiled from source. Maybe that has something to do with it?

**Comment by buwilliams** [comment]
homebrew

**Comment by mariusandra** [comment]
I finally managed to get my environment as stuck as well. All I had to do was to reboot :D.

No time to fix it now, but at least I have a place to start from.
