### ISSUE TITLE
Official method to health check the plugin server when installed via yarn

### ISSUE THREAD

**Issue by jeduden** [PostHog/plugin-server#372]
It seems, that the existing [healthcheck.ts](https://github.com/PostHog/plugin-server/blob/master/src/healthcheck.ts)  is only exposed via the docker container defined [here](https://github.com/PostHog/plugin-server/blob/master/Dockerfile). 
The posthog main repo also exposes the plugin server and installs it via [yarn in the dockerfile](https://github.com/PostHog/posthog/blob/master/production.Dockerfile#L18).

It would be great if the package could expose a binary `healthcheck` that calls [healthcheck.ts](https://github.com/PostHog/plugin-server/blob/master/src/healthcheck.ts).

This would enable the implementation of a healthcheck when the main image is executed with [bin/plugin-server](https://github.com/PostHog/posthog/blob/master/bin/plugin-server)

**Comment by Twixes** [comment]
Hey, just merged #455. Does that solve your use case?

**Comment by jeduden** [comment]
I think it should.  Is there a docker tag available to test this new code ?

**Comment by Twixes** [comment]
Not yet. This will be in the new PostHog version, 1.26.0 out next week, though – you may want to wait for that.

**Comment by jeduden** [comment]
Ok great ! I ll try it then ! Thanks a lot !
