### ISSUE TITLE
Plugin server is marked as not live while mmdb is being downloaded

### ISSUE THREAD

**Issue by macobo** [PostHog/plugin-server#391]
## Bug description

I want to deploy posthog. I boot posthog up, go through preflight and see this

![image](https://user-images.githubusercontent.com/148820/118166013-a59d2780-b42d-11eb-8eb9-0f05fca5df4d.png)

Looking at the logs, I see this:

```
[MAIN] 20:54:30 ⏳ Downloading GeoLite2 database from PostHog servers...
```

Which takes around a minute to resolve

## Expected behavior

Don't block preflight while mmdb is being downloaded

## How to reproduce

1. Boot a new posthog cluster
2. Go to preflight
3. See "warning" for plugin server, though plugin server is up

## Environment

- [x] self-hosted PostHog, version/commit: 1.25.0

**Comment by Twixes** [comment]
Maybe this should be a "loading" state, between "offline" and "online". Thing is, the plugin server is not really online if it's not able to ingest yet (why in this case: [point 6](https://github.com/PostHog/plugin-server/pull/247#issuecomment-804839689), so showing preflight as all green and allowing to proceed would be kind of premature. Unless the wait time is a significant source of friction (though it shouldn't be, actual deployments should be done with this in a few seconds, downlink is fast in data centers).

**Comment by macobo** [comment]
> Unless the wait time is a significant source of friction

It has been development-wise. It takes 1-2 minutes to download mmdb after a fresh database purge, adding a ton of waiting around to get to a good state. I've needed to recreate my dbs quite often (multiple times per day) when playing with clickhouse migrations, custom stats, etc and this has been the most painful part about it.

**Comment by Twixes** [comment]
I see. I suppose in your case you can just use `DISABLE_MMDB=1` and this won't be happening. Would that work for you?
Arguably we now preinstall & preenable the GeoIP plugin regardless of this setting (as it's only used for such specific circumstances), but I'll adjust that so that there's no conflict.

**Comment by macobo** [comment]
That sounds like a fair workaround! :bow:
