### ISSUE TITLE
Make PostHog API available to plugins

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/plugin-server#401]
Making an issue just to have.

We should allow plugins to call the PostHog API. I think we could create an API key in the background and expose an octokit-like interface for calling the API.

**Comment by yakkomajuri** [comment]
Done

**Comment by jamesefhawkins** [comment]
Feels like it's worth updating some docs somewhere since this is a huge deal for plugin power no?

**Comment by yakkomajuri** [comment]
@jamesefhawkins yup, I do actually have a PR out:

https://github.com/PostHog/posthog.com/pull/1785

+ next sprint I'll spend some time making sure plugin docs are up-to-date & great
