### ISSUE TITLE
Release 1.26.0 2/2

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/plugin-server#402]
WIP. Just writing down some notes.

### PHP

- Review, test, and merge https://github.com/PostHog/posthog-php/pull/9

### Flutter

- Review, test, and merge https://github.com/PostHog/posthog-flutter/pull/10

### React Native

- Make a call on all dependency updates: https://github.com/PostHog/posthog-react-native

### iOS

- SPM https://github.com/PostHog/posthog-ios/issues/13#issuecomment-845411459

### posthog-js

- rageclicks https://github.com/PostHog/posthog-js/issues/228
- /sessionRecording https://github.com/PostHog/posthog-js/issues/183

## Plugin Server

- Retries when punishing plugins https://github.com/PostHog/plugin-server/issues/387
- last_updated_at for properties? https://github.com/PostHog/plugin-server/issues/375
- S3 job queue #399 
- PostHog API? #401
- Plugin server not live while downloading MMDB https://github.com/PostHog/plugin-server/issues/391
- Multiple files https://github.com/PostHog/plugin-server/issues/367

## posthog

- Plugins frontend? https://github.com/PostHog/posthog/issues/2965

## Individual Plugins

- More retry queues (check most used plugins)
- Background processing (buffer) for Customer.io plugin (longest execution per event)

**Comment by mariusandra** [comment]
- iOS: https://github.com/PostHog/posthog-ios/issues/13#issuecomment-845411459

**Comment by mariusandra** [comment]
Broadly I see us fighting around 4 different battles simultaneously the next 2 weeks:

1) Data lakes. Exports. Imports. All the data. Reliably. Many different services.
2) The deteriorating state of our libraries.
3) Keep the lights on work in the plugin server itself.
4) New developments that unblock a lot of things: installing plugins, action matching.

Data lakes is the big big business objective we must nail. We're pretty good with what we already support, but we could do more :). https://github.com/PostHog/plugin-server/issues/404 and https://github.com/PostHog/plugin-server/issues/406 are the most important important points this time. The S3 queue also needs to be finished https://github.com/PostHog/plugin-server/pull/399 for extra safety.

Yet we can't ignore the other things.

**Comment by Twixes** [comment]
Action matching in the plugin server (#235) implementation is well underway now, so that'll ship in this next sprint.
On a different note, after all this work on features I'd love to make sure Plugins docs are up to date and top notch (https://github.com/PostHog/posthog.com/issues/1396).
Besides that, happy to take on other tasks from the extensive board, to be discussed.

**Comment by mariusandra** [comment]
Priorities this sprint:

1. Data lakes. Exports. Imports. All the data. Reliably. Many different services.
2. The deteriorating state of our libraries.
3. Keep the lights on work in the plugin server itself.
4. New developments that unblock a lot of things: installing plugins, action matching.

Tasks sorted by priority for everyone:

Marius:
- Priority 1: [`exportEvents`](https://github.com/PostHog/plugin-server/issues/404) and ["run from the beginning"](https://github.com/PostHog/plugin-server/issues/406)
- Priority 2: PHP [feature flags](https://github.com/PostHog/posthog-php/issues/10) and [PSR-4](https://github.com/PostHog/posthog-php/pull/9), iOS [SPM](https://github.com/PostHog/posthog-ios/issues/13)

Michael:
- Priority 2: [Migrate to flutter 2](https://github.com/PostHog/posthog-flutter/pull/10), [world class plugin docs](https://github.com/PostHog/posthog.com/issues/1396).
- Priority 3: [mmdb loading issue](https://github.com/PostHog/plugin-server/issues/391), [plugins health check](https://github.com/PostHog/plugin-server/issues/372)
- Priority 4: [action event matching inside the plugin server](https://github.com/PostHog/plugin-server/issues/235)

Neil:
- Priority 2: [$snapshot events wrongly sent](https://github.com/PostHog/posthog-js/issues/231), [this.rageClicks](https://github.com/PostHog/posthog-js/issues/228), [`/sessionRecording?...`](https://github.com/PostHog/posthog-js/issues/183)
- Priority 4: [plugin installation step](https://github.com/PostHog/plugin-server/issues/405)

Yakko:
- Priority 0: rest and enjoy time with your family
- Priority 2: [postgres plugin](https://github.com/PostHog/plugin-repository/issues/11), [retries when punishing plugins that error](https://github.com/PostHog/plugin-server/issues/387), [customer.io buffer](https://github.com/PostHog/customerio-plugin/issues/1), [clean up rudderstack export](https://github.com/PostHog/plugin-repository/issues/15)

**Comment by paolodamico** [comment]
For the User Experience Team (Core Experience split on frontend),

- 🚀 Event and properties basic taxonomy. Li.
- Dashboard version control and commenting/collaboration (after taxonomy and pending if something else comes up from focus customers). Li.
- 🚀 New UI for graphs & tooltips. Sam.
- Legends. Sam (Paolo to help with UI/UX).
- Paolo TBD until we figure out our approach for focus customers.

**Comment by mariusandra** [comment]
Hi @paolodamico and welcome to the plugin server repo! You're welcome to stay :D

**Comment by paolodamico** [comment]
Hahaha oops! Wrong issue 🤦 , sorry for hijacking it.

**Comment by Twixes** [comment]
Sprint planned. https://github.com/PostHog/posthog/issues/4446
