### ISSUE TITLE
Update interface when erroring

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#411]
When you enable a plugin, but it immediately errors and disables itself, there's no visual feedback to the user. You must reload the plugins page and only then will the error be shown.

Such real-time events should happen real time on the plugins page. It should update itself when:
- a plugin error is added
- a plugin disables itself
- plugin logs get added where there were none before (maybe)

**Comment by Twixes** [comment]
The plugin logs point is a bit unclear to me. They are only shown in the logs drawer and in there they _are_ loaded live as they arrive. Is that what you meant?

**Comment by mariusandra** [comment]
That's why there's a "(maybe)" with that point. The idea is that if there are 0 logs for the plugin, no need to show the "logs" button. If the first `console.log` gets stored in the db, the button will appear.

Might not be the best, so totally up to whoever is working on this to decide how to go.

**Comment by Twixes** [comment]
Hm, well, there are logs of loaded/unloaded anyway, so I think we can just show Logs always. Also makes it obvious that Logs are even a thing.
