### ISSUE TITLE
Proposal: rename "server" to "hub".

### ISSUE THREAD

**Issue by mariusandra** [PostHog/plugin-server#422]
The plugin server has a bunch of objects that it manages. A central one is called just ["server"](https://github.com/PostHog/plugin-server/blob/241a1a0f694c3d3b7bf1cf3cdad3c625074c406c/src/utils/db/server.ts#L25), which contains all connections to various databases and some adapters to query them (PG, Redis, ClickHouse, Kafka, etc). 

The name clashes with the "server" in ["plugin server"](https://github.com/PostHog/plugin-server/blob/409bf7a5f1596c7ed9b6186546a599a16632e39e/src/main/pluginsServer.ts#L33), which is the main entrypoint to the app.

Proposal: let's rename the connection object from "server" to "hub" to better reflect its intended usage.

**Comment by neilkakkar** [comment]
Agree with this: or `connections`. 

When first reading about the Plugin Server, I was very confused why there was a `server` inside the `PluginServer` that wasn't the `PluginServer.ts`

**Comment by Twixes** [comment]
Big +1, I was thinking about an alternative name for some time but didn't come up with anything solid, `hub` sounds reasonable. Created #425 which makes this change.

**Comment by mariusandra** [comment]
I thought of `connections` as well initially, but it's not descriptive enough IMO. Hub also contains logic and abstractions over the various connections, so... :).
