### ISSUE TITLE
State of benchmarks

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-server#430]
We have a CI suite called "Benchmarks". It's been added a while ago, and now my question is: what state are these benchmarks in really?

Personally, I've just never used them in any real way once they've been added and measured for the first time.
My only interaction has been that they occasionally fail due to a cosmic ray flipping a bit somewhere (not actually) and I have to rerun the GH Actions jobs.

So I was wondering:
@mariusandra Have you been finding the benchmarks useful?
Would making them more prominent (for example by having @posthog-bot post results on PRs) help their case?
Are their results relevant in their current form?

**Comment by mariusandra** [comment]
These benchmarks could have prevented one bug one time, had we seen the slowdown somewhere visually. A few times they as well caught some E2E-ish bugs. If we're running out of action runners, I'd be OK with disabling them. I think I fixed the flakey one with one of the last PRs, so if they don't bother us much, I'd let them stay.
