### ISSUE TITLE
Fire core webhooks and Zapier triggers from plugin server

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-server#459]
Direct followup to #235. Requirement of action matching in plugin server rollout.

**Comment by neilkakkar** [comment]
A question about the context here: Were we already firing webhooks in `PostHog/posthog` earlier, which gets replaced by the same in plugin-server? If so, can you please point me to where this was happening?

And, general question about actions: I couldn't figure out how webhooks come into play here? Didn't find an option for a callback url, or something related when creating actions. So: How do I setup webhooks/Zapier?

**Comment by Twixes** [comment]
Yep, we are currently firing webhooks from https://github.com/PostHog/posthog/blob/master/posthog/tasks/webhooks.py (Postgres, only webhooks) or https://github.com/PostHog/posthog/blob/master/ee/tasks/webhooks_ee.py (ClickHouse, webhooks + Zapier). Thanks to #479 (and all the work on action matching here before), Postgres and ClickHouse hooks will be fired from the same place, without need for offloading that via Celery.

As for the second part, what do you mean by setting up?
