### ISSUE TITLE
Retry plugin loading on ANY error

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-server#471]
After #460 we now nicely retry loading the plugin if `setupPlugin` throws a `RetryError`. This however requires very explicit usage of `RetryError` – even I forgot to do that and was confused for a moment until I recalled I need to throw the specific error. Actually, I believe we could safely retry on _any_ error and that could be a better dev experience. WDYT?

**Comment by yakkomajuri** [comment]
I think :thisismaybefine: and certainly better from a dev experience perspective - although we'll keep retrying things like invalid input from user too, so there will probably be a lot of retrying going on. We could also have a different policy for retry and non-retry errors?

**Comment by yakkomajuri** [comment]
Closing this as I think `RetryError` is fine and sets the tone for `RetryError` being used elsewhere. Feel free to reopen.
