### ISSUE TITLE
Race condition in ingestion pipeline

### ISSUE THREAD

**Issue by macobo** [PostHog/plugin-server#502]
I've been auditing person/person_distinct_id ingestion due to https://github.com/PostHog/posthog/issues/4242 and https://github.com/PostHog/product-internal/issues/2.

I believe these are all caused by race conditions within ingestion rearing it's head. 

One such bug stuck out to me reading through `src/worker/ingestion/process-event.ts`: 
https://github.com/PostHog/plugin-server/blob/ef130c3a53386f3f2e255cacbde86477611a5f4d/src/worker/ingestion/process-event.ts#L352-L382

Ignoring all the edge cases here, this code:
1. Updates cohortpeople table
2. Fetches all distinct_ids for the person to merge (SELECT)
3. For every one "moves" them (UPDATE query + KAFKA insert)
4. Finally deletes person

This flow can leave behind "distinct_ids" attached to a person if while step 3 or 4 are executing, a new distinct_id is added to the `otherPerson`. 

## How to fix

Proposed flow:
- Update cohortpeople table
- Delete person as step 2.
- Rather than query-per-distinctId, use `INSERT INTO ON CONFLICT IGNORE RETURNING *` query to replace steps 2-3.

Alternatively we could grab some sort of a relevant lock on person row whenever adding a distinctId or merging, which shouldn't slow ingestion down a lot.

cc @Twixes who ported the logic from python

**Comment by Twixes** [comment]
Hm, as described in the comment, the retry loop logic there now (added in https://github.com/PostHog/plugin-server/pull/474 – previously it was the same as it was in Python) should prevent the above race condition for messing data up, because Postgres raises an integrity error if trying to delete a person which still has distinct IDs assigned. Then the merging is ran again, for that dangling ID specifically. Am I missing something?

**Comment by macobo** [comment]
Good point, didn't consider that :sweat_smile: 

The while(true) loop does not work quite like advertised because of the following:
https://github.com/PostHog/plugin-server/blob/ef130c3a53386f3f2e255cacbde86477611a5f4d/src/utils/db/db.ts#L468-L470

If another distinct_id gets added during step 3, then that distinct_id is also deleted via the above line, resulting in no `DatabaseError`. Only when a distinct_id gets added inbetween running first and second DELETE.
