### ISSUE TITLE
Be less eager to disable an erroring plugin

### ISSUE THREAD

**Issue by Twixes** [PostHog/plugin-server#516]
Currently any non-`RetryError` error in a plugin causes it to be disabled. That's bad for data integrity – it creates a lot of opportunities for the plugin to be disabled and [we also don't report that happening](https://github.com/PostHog/plugin-server/issues/515).

Before going with this drastic step, we should try retrying even if it's not a `RetryError`. This should apply to plugin loading, unloading, event processing, jobs, basically any operation with potential to disable the plugin.

This problem was brought up by a current user of our Snowflake Export Plugin.

**Comment by neilkakkar** [comment]
Makes sense, another user had this problem as well: https://posthogusers.slack.com/archives/G01JXEDAL22/p1627847768031300

**Comment by neilkakkar** [comment]
Prev discussion: https://github.com/PostHog/plugin-server/issues/471
